// GENERATED FILE - DO NOT EDIT MANUALLY
// This file will be regenerated by FlutterFire CLI.
//
// To regenerate, run:
//   flutterfire configure
//
// For setup instructions, see:
// https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform.
///
/// IMPORTANT: Replace these placeholder values with your actual Firebase
/// configuration by running `flutterfire configure` after creating your
/// Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web push notifications not configured yet.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not supported.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported.',
        );
      default:
        throw UnsupportedError(
          'Unknown platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxnKjvusGHrWwA_dk5b15i07ccQPXEJ2s',
    appId: '1:771833823540:android:74fe1e09c0a93d14e4e561',
    messagingSenderId: '771833823540',
    projectId: 'divvy-83361',
    storageBucket: 'divvy-83361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN82JVTDMK867jmAnFCJ04jl7vYBaikt8',
    appId: '1:771833823540:ios:a984997d2d32ca80e4e561',
    messagingSenderId: '771833823540',
    projectId: 'divvy-83361',
    storageBucket: 'divvy-83361.firebasestorage.app',
    iosBundleId: 'com.divvy.app',
  );
}
